name: moviles_api_parte4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoupt.png
    - assets/logounjbg.png
    - assets/plazavea.png
    - assets/metro.png
    - assets/tottus.png
    - assets/saga.png
    - assets/ripley.png
    - assets/marker.png
